### ISSUE TITLE
Where is the code snippet for extracting relationship descriptor?

### ISSUE THREAD

**Issue by askerlee** [ZiqinZhou66/ZegCLIP#11]
Hi thanks for your work. Just want to quickly glance your code to understand how it works. But as I'm not familiar with its structure, I'm unable to find the code snippets for extracting the relationship descriptor. Could you please point that out for me? Thank you very much.

**Comment by ZiqinZhou66** [comment]
Thanks for your interest of our work. Please find the relationship descriptor in this function: https://github.com/ZiqinZhou66/ZegCLIP/blob/9ba4bb5c9b621c04005fb9cef7254e79bb9c9991/models/decode_heads/decode_seg.py#L325

**Comment by askerlee** [comment]
Great, thanks.
