### ISSUE TITLE
License

### ISSUE THREAD

**Issue by hamilton73** [ZiqinZhou66/ZegCLIP#5]
Thank you for providing the source code for this amazing project! In order to allow people to also use your code, can you please add a software license such as the MIT license? Otherwise, no one is legally allowed to work with your code (https://choosealicense.com/no-permission/). You can find further information provided by GitHub here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by ZiqinZhou66** [comment]
Thank you for the kind reminder. I have added an MIT license.

**Comment by hamilton73** [comment]
Thank you!
